#Lista de productos
stock = [{"ID":"AA0054",
          "nombre":"Arroz",
          "categoria":"Almacen",
          "precio":123.0,
          "stock":20},
         {"ID":"CC5689",
          "nombre":"Cacao",
          "categoria":"Almacen",
          "precio":456.0,
          "stock":50},
         {"ID":"TT3245",
          "nombre":"Té",
          "categoria":"Almacen",
          "precio":789.0,
          "stock":30}]
